[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.1"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "2.0.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  branch = "master"
  name = "github.com/tmc/scp"

[[constraint]]
  branch = "master"
  name = "gitpct.epam.com/epmd-aepr/aos_servicemanager"
  source = "git@gitpct.epam.com:epmd-aepr/aos_servicemanager.git"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
